<a href="https://colab.research.google.com/github/chacha86/bigData1/blob/main/numpy%20%EC%82%AC%EC%9A%A9%EB%B2%952.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 배열의 연산
import numpy as np

np.random.seed(1)
arr1 = np.random.randint(-10, 10, (3,4))

# 기초 통계 연산
arr1.mean()
arr1.max()
arr1.min()
arr1.sum()

np.random.seed(100)
arr2 = np.random.randint(-10, 10, (3,4))

print(arr1)
print(arr2)

# 두 배열의 연산 - 사칙 연산
arr3 = arr1 + arr2
arr4 = arr1 - arr2
arr5 = arr1 * arr2
arr6 = arr1 / arr2
arr7 = arr1 % arr2


# 배열의 값을 절대값으로
arr2 = np.abs(arr2)

print(arr2)

# arr1원소의 값을  arr2 원소만큼 제곱
arr9 = arr1 ** arr2


# 배열의 원소의 제곱근
arr10 = np.sqrt(arr2)

print(arr1 * arr2)

# 행렬의 점곱(dot product)
# (2 X 3) . (3 X 4)
# 3 4 3 4
arr1.shape
arr2.shape

# 행렬의 모습을 바꾸고 싶다. - reshape(행렬의 모양)
arr2 = arr2.reshape([4,3])
np.dot(arr1, arr2)

# 두 행렬의 비교
arr1 == arr2
print(arr2.size)

# reshaep 배열의 모양을 바꿀 때 사용. 원소의 개수에 주의
arr2 = arr2.reshape([3, -1])
arr2.shape


# 각 행렬의 원소 일치 여부
arr1 == arr2

# shape이 같은 두 행렬을 == 비교하면 각 원소의 일치 여부
np.array_equal(arr1, arr2)



In [ ]:
# 1차원 배열 -> 벡터
arr3 = np.arange(1, 16)
arr3.size
arr3.ndim

arr3 = arr3.reshape((3,-1))
arr3 = arr3.reshape((5, 3, -1))


In [66]:
arr1 = np.arange(1, 12)

# 차원 확장 및 축소
# 확장
arr2 = np.expand_dims(arr1, axis=0)
arr3 = np.expand_dims(arr1, axis=1)

# 축소
np.squeeze(arr2, axis=0)
np.squeeze(arr3, axis=1)




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
# 정렬

np.random.seed(1)
arr = np.random.randint(1, 100, 12)

#arr.sort() # 원본에 적용

arr2 = np.sort(arr) # 원본에 적용 X

arr
arr2


# arr
# arr[::-1]
[3,4]
arr3 = arr.reshape()

np.sort(arr3, axis=0)[::-1]
np.sort(arr3, axis=1)

# argsort()

idx = arr.argsort()[::-1]
arr[idx[:5]]



array([80, 77, 76, 73, 72])

In [146]:
# 배열 붙이기, 나누기
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)

print(arr1)
print(arr2)

arr3 = np.expand_dims(arr1, axis=0)
arr4 = np.expand_dims(arr2, axis=0)

arr5 = arr1.reshape(2,2)
arr6 = arr2.reshape(2,2)

np.concatenate((arr5, arr6), axis=1)

arr7 = np.arange(1, 13)

arr8  =arr7.reshape(3,4)


arr8
print(arr8)

print(np.split(arr8, 2, axis=1))
print(np.split(arr8, 1, axis=0))





[1 2 3 4]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])]
